apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: springboot-template
  title: Spring Boot Microservice
  description: Scaffold a basic Spring Boot service
  tags:
    - java
    - springboot
spec:
  owner: user:guest
  type: service

  parameters:
    - title: Información del componente
      required:
        - componentId
        - groupId
        - artifactId
        - version
        - description
      properties:
        componentId:
          type: string
          title: Nombre del componente
        groupId:
          type: string
          title: GroupId del proyecto (paquete base)
        artifactId:
          type: string
          title: ArtifactId raíz (nombre del microservicio)
        version:
          type: string
          title: Versión
          default: 1.0.0-SNAPSHOT
        description:
          type: string
          title: Descripción del microservicio

  steps:
    - id: fetch
      name: Descargar template
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: .
        templateEngine: cookiecutter
        values:
          componentId: '{{ parameters.componentId }}'
          groupId: '{{ parameters.groupId }}'
          artifactId: '{{ parameters.artifactId }}'
          version: '{{ parameters.version }}'
          description: '{{ parameters.description }}'

    - id: publish
      name: Publicar en GitHub
      action: publish:github
      input:
        repoUrl: github.com?repo={{ parameters.componentId }}&owner=nitsugamg83
        repoVisibility: public
